### ISSUE TITLE
Each run different output

### ISSUE THREAD

**Issue by zeynelsamak** [wuhuikai/TF-A2RL#3]
Hello,
Firstly, thanks for such great works.
I wonder why each run it provides different result for a same image?
Cheers

**Comment by DebangLi** [comment]
@zakamas Because the action is chosen by  multinomial sampling, so, there is randomness in the cropping process. If you want to have the same results for a single image, you can replace the multinomial sampling with choosing the action with the highest probability. The change can be done in "network.py"

**Comment by zeynelsamak** [comment]
Thank you @DebangLi , that's very helpful. I got it.
